### ISSUE TITLE
Support online map sources 

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-collector#119]
Currently the application only renders a map when offline map tiles are available. In order to support map display in the browser and allow users to load tiles from the web, we should support online map sources as well.

**Comment by jmunowitch** [comment]
https://github.com/archesproject/arches-mobile/blob/97df986098e1bb9b34a5af989df04ff9263957f8/src/app/projects/components/ProjectMapPage.vue#L83. This should be a variable that is passed from an Arches instance to the mobile app instead of being hard coded in here.
