### ISSUE TITLE
Navigating away from a report can require multiple taps on the back button.

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-collector#270]
Depending on the state of the navigation history stack, if a user is on a report, many taps on the back button may be required to back the user to the resource instance types page.

It would seem in most cases that users probably want to go back to the resource instance list, rather than resource type list, and that this just requires one click on the back button rather than moving through the history stack.

**Comment by ajwuthrich** [comment]
A possible UI Change could also include the following:
- When a user finishes creating a new resource instance and hits back, they are navigated to the resource instance list. Instead, they could be navigated back to the resource instance type list where they can create another resource instance.

- When a user edits an existing resource instance and clicks the "back" button, they are navigated to the resource instance type list, which promopts them to create a new resource instance. Instead, in this use case, the back button should navigate the user to the resource instance list where they can select and edit other existing resource instances.

**Comment by apeters** [comment]
fixed in the latest
