### ISSUE TITLE
Prevent provisional users from deleting authoritative tiles in the mobile app

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-collector#286]
In the web app, provisional users are not allowed to delete tiles with authoritative data. However, they can do this  on the mobile app. We need to know on the mobile app if a user is provisional and prevent them from deleting authoritative data.

**Comment by chiatt** [comment]
Works as expected

**Comment by chiatt** [comment]
Currently users can delete tiles that have been downloaded from the server.

**Comment by apeters** [comment]
meets requirements
