### ISSUE TITLE
Cards that allow multiple data sets are not cleared 

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches-collector#310]
When creating a new resource instance, data added to a card that allows for multiple data points (i.e Dimensions) will carry over to the next instance of the card that is added. In the example of the dimensions card, the first data set that is entered will start out with a blank form, but when the user tries to add a second data set to the card, the form will still contain the data from the first data set (It is dirty). 

This issue also occurs when editing an existing resource instance and inputting more than one new data set. 

http://g.recordit.co/Mcdl3A5z2A.gif

**Comment by chiatt** [comment]
Works as expected
