### ISSUE TITLE
[Map] Resource instances added in the mobile app do not show up on the project map

### ISSUE THREAD

**Issue by ajwuthrich** [archesproject/arches-collector#325]
Resource instances that are given spatial data do not display that data on the overall project map despite being in the resource instance list.

The Project map should display all of the locations of the resource instances provided that they have spatial data attributed to them. This is the case on the Xcode emulator and the phone deployment.

**Comment by chiatt** [comment]
@ajwuthrich Could it be that the limit set in the mobile survey was too low relative to the number of instances in the project bounds? By that I mean if the limit was set to 10, but there were thirty resources in the project bounds, 20 would not be added to the app.

**Comment by ajwuthrich** [comment]
@chiatt the limit was 100 and there were no instances on the map.

**Comment by dwuthrich** [comment]
meets requirement
