### ISSUE TITLE
Unable to delete or modify geometries in the map widget on a device

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-collector#328]
In the web emulator, users can edit and delete geometries in the map widget. On an iOS device (iPhone SE specifically - not tested on Android), it does not appear possible. A user can place the geometry in the selection state and then press delete, but there is no response. Trying to move the geometry or a vertex in the geometry only pans the map.

This example works on an iOS device: https://docs.mapbox.com/mapbox-gl-js/example/mapbox-gl-draw/

So, maybe the issue is related to the geometry saving automatically when in the process of editing?

**Comment by apeters** [comment]
I'm seeing the same issue on an Android device

**Comment by robgaston** [comment]
I'm pushing this ticket through in favor of two tickets for known outstanding issues: #456 & #457

**Comment by dwuthrich** [comment]
meets requirement
