### ISSUE TITLE
Gracefully truncate Instance Names

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-collector#350]
Currently, long instance names run-off the side of the mobile UI and obscure the button used to access the split panel as shown below.

The mobile app should use ellipsis ("...") to show that a name has been truncated.  This may be required for the navigation header (e.g.: "the Lincoln City/CGI Lincoln Survey" string).

![Screen Shot 2019-01-24 at 11.02.02 AM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/1c658f67-db1a-48de-8379-4a597df1e435)

**Comment by dwuthrich** [comment]
@apeters We still need to support this for the app header (e.g.: App nickname / survey name)

**Comment by chiatt** [comment]
@dwuthrich I've merged in a fix that truncates the survey name if it's too long. If the app name is too long, the survey name can still be pushed beyond the edge of the header element, but the user has control of the app name and can change it to something shorter if they like.

**Comment by dwuthrich** [comment]
meets requirement
