### ISSUE TITLE
Alert user when attempting to sync data to a deleted survey

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-collector#388]
A user gets no visible feedback that they are trying to synch data to a deleted survey.  To reproduce:

1. Create a survey, synch to a local device
2. Create new instances on the device
3. Delete the survey in the MSM
4. Sync data from the device.  Notice that the device looks as if it is synching data but does not alert the user that the survey does not exist.  Only indication of a deleted survey is when the user refreshes the app at the project level (at which time the device shows the survey as inactive).

The device should be able to display whether a survey is inactive (and still allows synching but no new downloads), and when the survey has been deleted (and no new data can be synched)

**Comment by chiatt** [comment]
re #401

**Comment by apeters** [comment]
meets requirements
