### ISSUE TITLE
On iOS, user can't delete an instance

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-collector#390]
To reproduce:

1. On an iOS device, create a new instance in a project
2. Try to delete the instance by pressing the "trash" icon
3. Note that the app interprets the interaction as a touch on the instance list item, and returns the user to instance editor

This means that the user can't delete an instance.

**Comment by chiatt** [comment]
When trying to click the trash can icon to delete data, it’s too hard to click it to delete (on project review page and on recently created tiles).

Padding around these elements should be increased to make interactions easier.

**Comment by dwuthrich** [comment]
meets requirement
