### ISSUE TITLE
Project name truncated on create resource page

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches-collector#460]
The project name is getting truncated unnecessarily in the header of the resource create page. See attached image.![Screen Shot 2019-02-19 at 3.19.07 PM.png](https://images.zenhubusercontent.com/56f0760d6caf56c9d38e0f81/74f19f5d-6c33-4e94-b777-95365f975c53)

**Comment by dwuthrich** [comment]
@ryan86 This is fixed in the latest
