### ISSUE TITLE
Arches collector: Report page shows map popup panel in the wrong spot

### ISSUE THREAD

**Issue by dwuthrich** [archesproject/arches-collector#487]
See:

![Screen Shot 2019-02-23 at 3.14.11 PM.png](https://images.zenhubusercontent.com/56f1ad0a6caf56c9d38e1cbd/1420ce13-240e-4ed3-991c-6ef0c89df795)

What should happen: we should either disable display of the pop-up or place the pop-up panel relative to the bottom of the screen when a user clicks on a geometry in the report page

**Comment by apeters** [comment]
this looks to be disabled in the latest
