### ISSUE TITLE
User location is not available on android devices

### ISSUE THREAD

**Issue by chiatt** [archesproject/arches-collector#524]
Android users cannot see nor zoom to their location on the map. When a user presses the user location button on the map, an error in the console indicates that the app does not have permissions to access the user's location. It is possible that the requested permissions need to be added to the the config.xml file as we do for iOS:

```
    <edit-config file="*-Info.plist" mode="merge" target="NSLocationWhenInUseUsageDescription">
        <string>need location access to find things nearby</string>
    </edit-config>
```

**Comment by apeters** [comment]
fixed in the latest
