### ISSUE TITLE
On Android, typing in dropdown fields doesn't narrow choices

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches-collector#527]
**Describe the bug**
On Android, typing in dropdown fields doesn't narrow choices...
![Screenshot_20190703-121525_ArchesCollector](https://user-images.githubusercontent.com/9683819/60632745-257ef300-9dbc-11e9-8097-732c3de81846.jpg)

**Comment by chiatt** [comment]
Hey @apeters, this is done, right? I'm going to assign to @adamlodge to QA.

**Comment by adamlodge** [comment]
meets reqt
