### ISSUE TITLE
Files not being associated with tileid in files table when uploaded from mobile app

### ISSUE THREAD

**Issue by ryan86** [archesproject/arches-collector#532]
**Describe the bug**

When a user uploads a tile of datatype file from the mobile app it is synced to the files table without a tileid. The effect of this is that when that tile is deleted from Arches the file is not deleted from the files table or the file system.

**To Reproduce**
1. Create a resource with the mobile app, that includes a file-list datatype
2. Sync this resource to Arches
3. Go to the files table and observe there is a file with no associated tileid
4. Delete the resource/tile from Arches, observe the record has not been deleted from the files table and the file itself has not been removed from the file system.

**Screenshots**

**Expected behavior**
The file record from the files table and the file itself should removed from the database and the file system respectively.

**Your Arches Information**

*   Version used: 4.4.x
*   Operating System and version (iOS or Android): iOS, Ubuntu 18
*   Link to your Arches Install (optional): 

**Additional context**

**Ticket Background**
*   Found by: @

**Comment by chiatt** [comment]
Closing because this bug was in Arches 4.4
