### ISSUE TITLE
android app crashes when taking photo

### ISSUE THREAD

**Issue by adamlodge** [archesproject/arches-collector#535]
**Describe the bug**
SF Planning interns have observed that andoird app crashes when you take a photo for use in the file widget.

**Comment by chiatt** [comment]
This may be due to limited memory on the device.

**Comment by chiatt** [comment]
Hey Adam - I'm going to leave this in QA. When the SF team gets new devices, we can check if it's still a problem. Hopefully it's just a matter of device resources and we can then close this.

**Comment by adamlodge** [comment]
no feedback from SF.  I'm closing.
