### ISSUE TITLE
Arches should allow admins to set a limit of the resolution of images uploaded by Collector

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-collector#563]
Harvest: Task 2

**Comment by chiatt** [comment]
@apeters The resolveLocalFileSystemURL method fails to retrieve a file object on iOS, and therefore is unable to resize the image.

**Comment by whatisgalen** [comment]
In reproducing, I uploaded a 5mb image, synced, then downloaded the image from arches resource editor, and noted that the filesize was (2mb). I had not altered the default settings in arches:
```
MOBILE_IMAGE_SIZE_LIMITS = {
    # These limits are meant to be approximates. Expect to see uploaded sizes range +/- 20%
    # Not to exceed the limit defined in DATA_UPLOAD_MAX_MEMORY_SIZE
    "full": min(1500000, DATA_UPLOAD_MAX_MEMORY_SIZE),  # ~1.5 Mb
    "thumb": 400,  # max width/height in pixels, this will maintain the aspect ratio of the original image
}
```

**Comment by apeters** [comment]
Calculating the file size on disk is not an exact science.  2Mb is in the realm of +/- 20% of 1.5 Mb.  I'm ok with closing this for now
