### ISSUE TITLE
Implement bi-directionality during Collector project sync operations

### ISSUE THREAD

**Issue by apeters** [archesproject/arches-collector#565]
This is obviously a very large task and the first thing to do would be to propose a solution and then identify smaller subtasks from that.

Harvest: Task 3

**Comment by whatisgalen** [comment]
in reproducing:

change made on resource in collector --> synced --> visible in arches (OK)
change made on resource in arches --> synced --> (possible bug):
- the name node was edited (thus should generate new display name as it's the triggering nodegroup for the resource name descriptor)
- after sync, collector shows the resource instance with the original, unchanged displayname (bug?)
- on click, the tiledata reflects the change made in arches (OK)
- going back, the display name is updated to reflect the change (OK)

**Comment by whatisgalen** [comment]
Except for the above and #605 this works as expected

**Comment by apeters** [comment]
I could not reproduce the error above with the displayname not updating properly nor with the geometry widget infinitely loading (#605), closing for now
